version: "2"
sql:
  - engine: "postgresql"
    queries: "./queries"
    schema: "./migrations"
    gen:
      go:
        out: "."
        package: "pgstore"
        sql_package: "pgx/v5"
        emit_json_tags: false
        emit_db_tags: true
        emit_exact_table_names: true
        overrides:          
          - db_type: "uuid"
            nullable: true
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
